version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todo-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

volumes:
  mongodb_data:
    driver: local

networks:
  todo-network:
    driver: bridge 